### ISSUE TITLE
PDM to PCM to DAC

### ISSUE THREAD

**Issue by hananabilabd** [alanbarr/stm32f4_mic_eth#2]
I am using STM32F446RC MCU 
and I am trying to wire the MEMS microphone directly through the I2S , but I don't know  how to redirect this acquired PCM to DAC , I get nothing except noise 
Any help

**Comment by alanbarr** [comment]
Sorry, I haven't tried using the DAC. All I can suggest is you first try and output a clean sine wave from RAM to the DAC then take it from there. It'd be best trying this with the same clock configurations required for the MEMS microphone in case there is a conflict.

**Comment by hananabilabd** [comment]
I output the audio coming from MEMS mic now to the DAC and the sound is good to hear  ,, and the gain is perfect ,, but there is a lot of noise , 
I am asking where can I found the parameters to the PDMtoPCM library cause , I read all the datasheet related and the documentation is really poor ,, I tried to apply the values from equations in the MEMS examples they are providing ,, but even worse ,, 
I am using STM32F446RC , with 16 MHZ external , 180 MHz as sysclk ,, 120MHz to the I2S clk 
the I2S clk pin output nearly 3.05 MHZ I tried decimation factor 64 & 32 ( supposed that 64 gives 48 khz sampling frequency and 32 gives 96 sampling frequency ) 
- I don't know why should I put the output samples in PDMtoPCMFilter ---> (AUDIO_SAMPLING_FREQUENCY/1000) * N_MS_PER_INTERRUPT 
- what values did you try ?

**Comment by hananabilabd** [comment]
@alanbarr

**Comment by alanbarr** [comment]
By PDMtoPCM library are you referring to: libPDMFilter (see [AN3998](https://www.st.com/content/ccc/resource/technical/document/application_note/ca/18/be/bb/f8/53/47/a5/DM00040808.pdf/files/DM00040808.pdf/jcr:content/translations/en.DM00040808.pdf)) ?
If so there's going to be a trade off of quality for performance there. 

I recall that it produced a pretty noisy signal, but unfortunately I don't think I still have the configuration used when testing it.

For more information on using libPDMFilter, your best bet might be ST forums.

**Comment by hananabilabd** [comment]
@alanbarr Thanks 
but really with the discovery board MIC and the sound was pretty noisy ?

**Comment by alanbarr** [comment]
I recall libPDM (IIR) not being as clean as a FIR filter, but can't remember anything more than that.
However, skimming the application note I'm not sure you're using libPDM?

> I tried decimation factor 64 & 32 ( supposed that 64 gives 48 khz sampling frequency and 32 gives 96 sampling frequency )

Where are you getting 32 from? AN3998 states it supports a decimation factor of 64 or 80:

> There are four different implementations of this function depending on the decimation factor
(64 or 80) and on the LSB or MSB representation of the input buffer.

**Comment by hananabilabd** [comment]
@alanbarr  I am using PDM2PCM library 
![image](https://user-images.githubusercontent.com/26032494/57773219-d13e8780-7717-11e9-8766-6f63b66a642e.png)
![image](https://user-images.githubusercontent.com/26032494/57773248-ddc2e000-7717-11e9-905a-561650c05bd1.png)
and I am using [AN5027](https://www.st.com/content/ccc/resource/technical/document/application_note/group0/7d/62/3d/ad/24/57/47/78/DM00380469/files/DM00380469.pdf/jcr:content/translations/en.DM00380469.pdf)


> I recall libPDM (IIR) not being as clean as a FIR filter, but can't remember anything more than that.
> However, skimming the application note I'm not sure you're using libPDM?

I can't find the libPDM (IIR) you are talking about
I think AN3998 is an outdated application note released in 2011 m but even the api stated in it , is now changed
